CREATE TABLE articles (
  id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  title TEXT,
  CONTENT TEXT,
  user_email TEXT,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, NOW()) NOT NULL
);
 
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
 
CREATE policy "Users can create articles." ON articles FOR
  INSERT WITH CHECK (auth.uid() = user_id);
 
CREATE policy "Users can update their own articles." ON articles FOR
  UPDATE USING (auth.uid() = user_id);
 
CREATE policy "Users can delete their own articles." ON articles FOR
  DELETE USING (auth.uid() = user_id);
 
CREATE policy "Articles are public" ON articles FOR
  SELECT USING (TRUE);
